//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWalker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWalker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicPS {
            get {
                object obj = ResourceManager.GetObject("BasicPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicPS_Deferred {
            get {
                object obj = ResourceManager.GetObject("BasicPS_Deferred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_Box {
            get {
                object obj = ResourceManager.GetObject("BasicVS_Box", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_Capsule {
            get {
                object obj = ResourceManager.GetObject("BasicVS_Capsule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_Cylinder {
            get {
                object obj = ResourceManager.GetObject("BasicVS_Cylinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCCT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCCTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCCTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCTTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCTTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PBBNCTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PBBNCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCTTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCTTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCTTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCTTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCCTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCTTT {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCTTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCTTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCTTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCTTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_PNCTX {
            get {
                object obj = ResourceManager.GetObject("BasicVS_PNCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicVS_Sphere {
            get {
                object obj = ResourceManager.GetObject("BasicVS_Sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoundingBoxVS {
            get {
                object obj = ResourceManager.GetObject("BoundingBoxVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoundingSphereVS {
            get {
                object obj = ResourceManager.GetObject("BoundingSphereVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoundsPS {
            get {
                object obj = ResourceManager.GetObject("BoundsPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CablePS {
            get {
                object obj = ResourceManager.GetObject("CablePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CablePS_Deferred {
            get {
                object obj = ResourceManager.GetObject("CablePS_Deferred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CableVS {
            get {
                object obj = ResourceManager.GetObject("CableVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CloudsPS {
            get {
                object obj = ResourceManager.GetObject("CloudsPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CloudsVS {
            get {
                object obj = ResourceManager.GetObject("CloudsVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DirLightPS {
            get {
                object obj = ResourceManager.GetObject("DirLightPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DirLightPS_MS {
            get {
                object obj = ResourceManager.GetObject("DirLightPS_MS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DirLightVS {
            get {
                object obj = ResourceManager.GetObject("DirLightVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DistantLightsPS {
            get {
                object obj = ResourceManager.GetObject("DistantLightsPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DistantLightsVS {
            get {
                object obj = ResourceManager.GetObject("DistantLightsVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightPS {
            get {
                object obj = ResourceManager.GetObject("LightPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightPS_MS {
            get {
                object obj = ResourceManager.GetObject("LightPS_MS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightVS {
            get {
                object obj = ResourceManager.GetObject("LightVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LodLightsPS {
            get {
                object obj = ResourceManager.GetObject("LodLightsPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LodLightsPS_MS {
            get {
                object obj = ResourceManager.GetObject("LodLightsPS_MS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LodLightsVS {
            get {
                object obj = ResourceManager.GetObject("LodLightsVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MarkerPS {
            get {
                object obj = ResourceManager.GetObject("MarkerPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MarkerVS {
            get {
                object obj = ResourceManager.GetObject("MarkerVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathBoxPS {
            get {
                object obj = ResourceManager.GetObject("PathBoxPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathBoxVS {
            get {
                object obj = ResourceManager.GetObject("PathBoxVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathDynVS {
            get {
                object obj = ResourceManager.GetObject("PathDynVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathPS {
            get {
                object obj = ResourceManager.GetObject("PathPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathVS {
            get {
                object obj = ResourceManager.GetObject("PathVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPBloomFilterBPHCS {
            get {
                object obj = ResourceManager.GetObject("PPBloomFilterBPHCS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPBloomFilterVCS {
            get {
                object obj = ResourceManager.GetObject("PPBloomFilterVCS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPCopyPixelsPS {
            get {
                object obj = ResourceManager.GetObject("PPCopyPixelsPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPFinalPassPS {
            get {
                object obj = ResourceManager.GetObject("PPFinalPassPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPFinalPassVS {
            get {
                object obj = ResourceManager.GetObject("PPFinalPassVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPLumBlendCS {
            get {
                object obj = ResourceManager.GetObject("PPLumBlendCS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPReduceTo0DCS {
            get {
                object obj = ResourceManager.GetObject("PPReduceTo0DCS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPReduceTo1DCS {
            get {
                object obj = ResourceManager.GetObject("PPReduceTo1DCS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PPSSAAPS {
            get {
                object obj = ResourceManager.GetObject("PPSSAAPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShadowPS {
            get {
                object obj = ResourceManager.GetObject("ShadowPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShadowVS {
            get {
                object obj = ResourceManager.GetObject("ShadowVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShadowVS_Skin {
            get {
                object obj = ResourceManager.GetObject("ShadowVS_Skin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkydomePS {
            get {
                object obj = ResourceManager.GetObject("SkydomePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkydomeVS {
            get {
                object obj = ResourceManager.GetObject("SkydomeVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkyMoonPS {
            get {
                object obj = ResourceManager.GetObject("SkyMoonPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkyMoonVS {
            get {
                object obj = ResourceManager.GetObject("SkyMoonVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkySunPS {
            get {
                object obj = ResourceManager.GetObject("SkySunPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkySunVS {
            get {
                object obj = ResourceManager.GetObject("SkySunVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainPS {
            get {
                object obj = ResourceManager.GetObject("TerrainPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainPS_Deferred {
            get {
                object obj = ResourceManager.GetObject("TerrainPS_Deferred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCCT {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCCTT {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCCTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCCTTTX {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCCTTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCCTTX {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCCTX {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCTTTX {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCTTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVS_PNCTTX {
            get {
                object obj = ResourceManager.GetObject("TerrainVS_PNCTTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TreesLodPS {
            get {
                object obj = ResourceManager.GetObject("TreesLodPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TreesLodPS_Deferred {
            get {
                object obj = ResourceManager.GetObject("TreesLodPS_Deferred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TreesLodVS {
            get {
                object obj = ResourceManager.GetObject("TreesLodVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterPS {
            get {
                object obj = ResourceManager.GetObject("WaterPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterPS_Deferred {
            get {
                object obj = ResourceManager.GetObject("WaterPS_Deferred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterVS_PCT {
            get {
                object obj = ResourceManager.GetObject("WaterVS_PCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterVS_PNCT {
            get {
                object obj = ResourceManager.GetObject("WaterVS_PNCT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterVS_PNCTX {
            get {
                object obj = ResourceManager.GetObject("WaterVS_PNCTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaterVS_PT {
            get {
                object obj = ResourceManager.GetObject("WaterVS_PT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WidgetPS {
            get {
                object obj = ResourceManager.GetObject("WidgetPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WidgetVS {
            get {
                object obj = ResourceManager.GetObject("WidgetVS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
