name: Build grzyClothTool for supporters

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the action on"
        required: true
        default: "master"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.400"

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean
        run: dotnet clean

      - name: Build
        run: dotnet build

      - name: Publish application
        run: |
          dotnet publish ./grzyClothTool/grzyClothTool.csproj -c Release -r win-x64 --self-contained false --output ./publish `
          -p:PublishSingleFile=true `
          -p:PublishReadyToRun=true `
          -p:TargetFramework=net8.0-windows

      - name: Create Zip
        run: |
          cd publish
          powershell Compress-Archive -Path * -DestinationPath ../grzyClothTool-supporters.zip
          cd ..

      - name: Send notification to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }} # Ensure this secret is set in your GitHub repo
          MESSAGE_TEXT: "✅ Build grzyClothTool succeeded! Here is the build ZIP:"
        run: |
          # Set up the file path for the attachment
          set "attachment=./grzyClothTool-supporters.zip"
          set "message_text=%MESSAGE_TEXT%"
          curl -k -F "payload_json={\"content\": \"%message_text%\"}" -F "file1=@%attachment%" %WEBHOOK_URL%
